Adding bash completion to the CLI
Signed-off-by: Paulo Lopes <pmlopes@gmail.com>

diff --git a/pm/src/assembly/bin/es4x b/pm/src/assembly/bin/es4x
--- a/pm/src/assembly/bin/es4x
+++ b/pm/src/assembly/bin/es4x
@@ -52,6 +52,6 @@ fi
 if [[ -f "node_modules/.bin/es4x-launcher.jar" ]]; then
   exec "$JAVA_EXE" -XX:+IgnoreUnrecognizedVMOptions $JVMCI $SECURITY_MANAGER $LOGGING_PROPERTIES $JAVA_OPTS -cp "node_modules/.bin/es4x-launcher.jar:$basedir/../es4x-pm-${project.version}.jar" io.reactiverse.es4x.ES4X "$@"
 else
-  echo "Missing node_modules/.bin/es4x-launcher.jar"
+  echo "Missing node_modules/.bin/es4x-launcher.jar" >&2
   exit 3
 fi
